using System;
using System.Collections.Generic;
using IHI.Server.Habbos.Figure.Parts;

namespace IHI.Server.Plugins.Zak.StandardHabboFigures
{
    public class StandardHabboFigures : Plugin
    {
        public override void Start()
        {
            var partTypes = new List<Type>
                                {
                                    typeof (Body180),
                                    typeof (Hair145),
                                    typeof (AnaglyphGlasses),
                                    typeof (EyePatch),
                                    typeof (FutureStyleGlasses),
                                    typeof (NormalGlasses),
                                    typeof (SmallGlasses),
                                    typeof (SunGlasses),
                                    typeof (Bandanna),
                                    typeof (BigBeard),
                                    typeof (BigMoustache),
                                    typeof (GasMask),
                                    typeof (GreenMouthMask),
                                    typeof (HockeyMask),
                                    typeof (Moustache),
                                    typeof (NoseIten),
                                    typeof (PranksterItem),
                                    typeof (SmallBeard),
                                    typeof (TikkiMask),
                                    typeof (BearHat),
                                    typeof (BlueTurban),
                                    typeof (BunnyHat),
                                    typeof (ChefHat),
                                    typeof (ChristmasHat2),
                                    typeof (CowboyStyleHat),
                                    typeof (FashionHat),
                                    typeof (FruitHat),
                                    typeof (FurryRoundHat),
                                    typeof (GangsterHat),
                                    typeof (HardHat),
                                    typeof (HeadBand),
                                    typeof (Hood),
                                    typeof (NormalCap),
                                    typeof (OldClassicStyleWig),
                                    typeof (OldStyleHat),
                                    typeof (PaperBag),
                                    typeof (PomPomHat),
                                    typeof (RastaHat),
                                    typeof (RoundStyleHat),
                                    typeof (SantaHat),
                                    typeof (SkIMask),
                                    typeof (SunHat),
                                    typeof (UrbanHat),
                                    typeof (WrappedHat),
                                    typeof (BowTieHairStyle),
                                    typeof (ButterFly),
                                    typeof (DiamondEarings),
                                    typeof (Earphone),
                                    typeof (Feather),
                                    typeof (Flower),
                                    typeof (HeadSet),
                                    typeof (Horns),
                                    typeof (Star),
                                    typeof (Tiara),
                                    typeof (FashionSkirtFemale),
                                    typeof (LongSkirtWithStripesFemale),
                                    typeof (LongSkirtFemale),
                                    typeof (MiniSkirtFemale),
                                    typeof (PlainShorts),
                                    typeof (PlainTrousers),
                                    typeof (SportsShorts),
                                    typeof (TrackSuitBottoms),
                                    typeof (TrousersWithPockets),
                                    typeof (ArabicStyleTShirtLongSleeveFemale),
                                    typeof (ArabicStyleTShirtShortSleeveFemale),
                                    typeof (BasketballVestFemale),
                                    typeof (BasketBallVestMale),
                                    typeof (BraVestNoSleeveFemale),
                                    typeof (BraVestFemale),
                                    typeof (CardiganWithStripedTShirtLongSleeveFemale),
                                    typeof (CardiganWithStripedTShirtShortSleeveFemale),
                                    typeof (DesignerDressFemale),
                                    typeof (DesignerVestFemale),
                                    typeof (DotAndLaceShirtLongSleeveFemale),
                                    typeof (DotsAndLaceShirtShortSleeveFemale),
                                    typeof (FurryBraFemale),
                                    typeof (HoddyTopMale),
                                    typeof (JacketAndCheckTShirtLongSleeveMale),
                                    typeof (JacketAndCheckTShirtShortSleeveMale),
                                    typeof (LeatherBraJacketLongSleeveFemale),
                                    typeof (LeatherBraJacketShortSleeveFemale),
                                    typeof (LeatherJacketFemale),
                                    typeof (LeatherJacketMale),
                                    typeof (LongCoatWithButtonsFemale),
                                    typeof (LongSleeveBigBreastHeartTShirtFemale),
                                    typeof (LongSleeveButtonAndLaceStyleCoatFemale),
                                    typeof (LongSleeveButtonTShirtFemale),
                                    typeof (LongSleeveFlameTShirtMale),
                                    typeof (LongSleevePatternTShirtFemale),
                                    typeof (LongSleevePlainTShirtMale),
                                    typeof (LongSleevePocketTShirtMale),
                                    typeof (LongSleeveStarTShirtMale),
                                    typeof (LongSleeveStripedTShirtMale),
                                    typeof (LongSleeveTShirtFemale),
                                    typeof (LongSleeveTShirtMale),
                                    typeof (NormalSuitMale),
                                    typeof (RefreeTShirtFemale),
                                    typeof (RefreeTShirtMale),
                                    typeof (ShortSleeveBigBreastHeartTShirtFemale),
                                    typeof (ShortSleeveBiggerBreastTShirtFemale),
                                    typeof (ShortSleeveButtonAndLaceCoatFemale),
                                    typeof (ShortSleeveButtonTShirtFemale),
                                    typeof (ShortSleevedCollarTShirtMale),
                                    typeof (ShortSleeveFlameTShirtMale),
                                    typeof (ShortSleeveLaceShirtMale),
                                    typeof (ShortSleevePatternShirtFemale),
                                    typeof (ShortSleevePlainTShirtMale),
                                    typeof (ShortSleevePocketTShirtMale),
                                    typeof (ShortSleeveShirtMale),
                                    typeof (ShortSleeveSmallBreastStripedTShirtFemale),
                                    typeof (ShortSleeveStarTShirtMale),
                                    typeof (ShortSleeveStripedTShirtMale),
                                    typeof (ShortSleeveTShirtFemale),
                                    typeof (SportsTShirtFemale),
                                    typeof (SportsTShirtMale),
                                    typeof (StripedVestNoSleevesFemale),
                                    typeof (StripedVestNoSleeveMale),
                                    typeof (ShirtNoSleeveBigBreastFemale),
                                    typeof (VestWithBowFemale),
                                    typeof (WaistCoatWithLongSleeveAndTieMale),
                                    typeof (WaistCoatWithShortSleeveAndTieMale),
                                    typeof (WannaBeGangsterJacketMale),
                                    typeof (AwardBadge),
                                    typeof (BowTie),
                                    typeof (ChainNecklace),
                                    typeof (DesignerNecklace),
                                    typeof (DesignerPurpleNecklace),
                                    typeof (DiamondNecklace),
                                    typeof (DollarChains),
                                    typeof (ExpensiveNecklace),
                                    typeof (FlowerBadge),
                                    typeof (FuzzyScarf),
                                    typeof (KeyNecklace),
                                    typeof (NormalChain),
                                    typeof (NormalScarf),
                                    typeof (PeaceNecklace),
                                    typeof (PearlNecklace),
                                    typeof (StarBadge),
                                    typeof (Stehoscope),
                                    typeof (StripedTie),
                                    typeof (TiedScarf),
                                    typeof (BigTrainers),
                                    typeof (BlockLegoShoes),
                                    typeof (BunnyFlippers),
                                    typeof (Flippers),
                                    typeof (HighHeels),
                                    typeof (Slippers),
                                    typeof (SmartShoes),
                                    typeof (Trainers),
                                    typeof (BlackDesignerBelt),
                                    typeof (DesignerBuckleBelt),
                                    typeof (DesignerStyleBelt),
                                    typeof (ExpensiveBelt),
                                    typeof (HBuckleBelt),
                                    typeof (KarateStylebelt),
                                    typeof (NormalBelt),
                                    typeof (NormalBuckleBelt),
                                    typeof (SkullBelt),
                                    typeof (SpikeBelt),
                                    typeof (StarBelt),
                                    typeof (WhiteDesignerBelt)
                                };

            var factory = CoreManager.GetServerCore().GetHabboFigureFactory();
            foreach (var partType in partTypes)
            {
                factory.RegisterModelID(partType);
            }
        }
    }
}